### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by holgersindbaek** [ivanacostarubio/helu#1]
I'm still relatively new to Ruby Motion and I've been looking for something like this.

Could you possibly elaborate a bit more on the example you give in the read me? Maybe even make an example project?

**Comment by ivanacostarubio** [comment]
Sure. 

The code is quite simple. Have you tried it on your project?

 We must create two lambdas. One for when the purchase is suscessful and one for when there is an error. One of them will execute after we get a response from apple. 

I would love to create a better example for this. I'll setup a test project in the next couple of hours.

**Comment by holgersindbaek** [comment]
Sounds awesome. 

I haven't tried it yet. Just bought the RubyMotion license and I'm still playing around. Want to convert one of my larger apps to RubyMotion. 

Would be awesome to be able to use something like Helu. In-app purchase, is so annoying. This seems to make it pretty straight forward :-).

**Comment by ivanacostarubio** [comment]
Hey @holgersindbaek, 

You can find the example app at: 

https://github.com/ivanacostarubio/helu-example

Hit me up by email if you want some help converting the app or implementing auto-renewable subscriptions ivan at softwarecriollo.com
