### ISSUE TITLE
release 0.6?

### ISSUE THREAD

**Issue by jayroh** [ivanacostarubio/helu#11]
Hey @ivanacostarubio is there anything in master that would prohibit a new version of the gem being released? I _just_ noticed that `0.5`, what I've been messing around with locally, doesn't have the product info fetcher class and lost a little bit of time until I realized it.

If there's anything we could do to help, let us know!

**Comment by ivanacostarubio** [comment]
Hello @jayroh! 

There is nothing stopping us from releasing it. I'll do it before Monday. 

Cheers and happy weekend! :+1:

**Comment by jayroh** [comment]
Thank you, sir :)

On Fri, Aug 1, 2014 at 12:05 PM, Ivan Acosta-Rubio <notifications@github.com

**Comment by ivanacostarubio** [comment]
pushed to Rubygems :shipit: 

I did some testing here on ma machine and everything seems fine. It'll be great if I can get your support to test this release :beers:
