### ISSUE TITLE
Helu::ProductInfoFetcher hangs

### ISSUE THREAD

**Issue by jamonholmgren** [ivanacostarubio/helu#12]
Hey Ivan!

I had to use the underlying `SKProductsRequest`, because Helu::ProductInfoFetcher hangs for some reason. The `Helu.new` purchaser still works fine, though.

I'll submit a PR when I figure out what's going on but wanted to let you know about this problem. Maybe something to do with the mutex?

Jamon

**Comment by ivanacostarubio** [comment]
Hey James. 

I am looking forward to it. I haven't use that part of the gem in a while, but today I'll fire up a project with it and do a couple of tests. I'll report back.

**Comment by ivanacostarubio** [comment]
Hey @jamonholmgren, 

Were you able to dig deeper into what is going on? Maybe @wejn can help us debug why Helu::ProductInfoFetcher hangs.

**Comment by jamonholmgren** [comment]
Not yet @ivanacostarubio! Been dealing with other issues, and our more manual setup has worked so far, so it's a lower priority. :-/

**Comment by wejn** [comment]
@ivanacostarubio Thanks for the vote of confidence. Unfortunately I don't have the resources to do it now (last time I had working R-M setup was when I was finishing my first app --- about a year ago).
