### ISSUE TITLE
Auto-Renewable subscriptions

### ISSUE THREAD

**Issue by holgersindbaek** [ivanacostarubio/helu#2]
I need something like this for auto-renewable subscriptions.

Is auto-renewable subscriptions supported in hell?

**Comment by ivanacostarubio** [comment]
hell!!! :joy: That's exactly how I felt when implementing IAP on IOS. LOL 

I haven't used Auto-Renewable subscriptions on my app yet, but I would love to support this on Helu.

**Comment by holgersindbaek** [comment]
Sounds awesome. Any plans on when you'll implement it :-).

**Comment by ivanacostarubio** [comment]
Nope, but I'll be happy to look / merge any pull requests for it.
