### ISSUE TITLE
I want to make subscriptions for Helu

### ISSUE THREAD

**Issue by holgersindbaek** [ivanacostarubio/helu#3]
Any advices on where to start?

It's my first time contributing to a rubymotion gem. Any advice?

**Comment by ivanacostarubio** [comment]
Hey @holgersindbaek ! 

This is great news. Do you have subscriptions working on your app? If so, we can extract them from it.

**Comment by holgersindbaek** [comment]
No... I haven't implemented subscriptions yet. I've just "converted" my app to Rubymotion. 

In my Obj-C app, I've been using - https://github.com/MugunthKumar/MKStoreKit. Thinking about using that as a starting point.

**Comment by ivanacostarubio** [comment]
What would be the api we would like to have for this? 

``` ruby

Hule.new("product_id").subscribe 

```

I am not really sure. What are your thoughts?

**Comment by holgersindbaek** [comment]
Hi Ivan

You working on this as well?

I've refactored the code a big. You can check it out on my branch. I haven't made the code to actually subscribe yet... I'm starting on that later today.

For now, I've made it so you can actually check if the product is a "real" product and you can get the title, decription and (localized) price.

Right now I'm working on making receipt validation and after that I'll start on the subscription code.. Unless you wanna do that? :-)

**Comment by ivanacostarubio** [comment]
Hey @holgersindbaek 

We don't have plans of adding subscriptions on the app I am working on right now, but it'll be a plush to have it on Helu. I'll check out the branch.

**Comment by holgersindbaek** [comment]
Great. You can also wait until later today. Then I'll write the README as well, so things are a bit more obvious.

If you check it out, let me know what you think then.

**Comment by ivanacostarubio** [comment]
I am closing the issue in favor of just talking on a feature branch where we'll work on making subscriptions happen. :+1:
