### ISSUE TITLE
ProductInfoFetcher different behaviour on different device

### ISSUE THREAD

**Issue by n-studio** [ivanacostarubio/helu#7]
Hi all!

I tried this piece of code on 3 different devices, and I got 3 different behaviours...

```
@x = Helu::ProductInfoFetcher.fetch(["com.mycompany.myapp.100coins"]) do |pi|
  NSLog "#{pi}"
end
```

Simulator:
No log printed. I guess it's normal, some forum threads say that in app purchase in not testable on simulator...

iOS6 (jailbroken):
=> {}
Print an empty hash instead of the expected products.

iOS7 (not jailbroken):
=> {"com.mycompany.myapp.100coins"=>{:id=>"com.mycompany.myapp.100coins", :title=>"100 coins", :description=>"100 gold coins", :price=>100.0, :currency=>"JPY", :price_str=>"￥100"}}
Print the excepted hash.

Unfortunately, I don't have any other devices to test more. Does someone have a piece of explanation on why do I have an empty hash on iOS6 ?

Thanks a lot!

**Comment by ivanacostarubio** [comment]
Hello @n-studio 

It may have something to do with the phone being jailbroken?

**Comment by ivanacostarubio** [comment]
@n-studio Have you pin point this issue to the phone being jailbroken? I am able to get the product's info, but storekit is a wild beast :)

**Comment by n-studio** [comment]
I've found an unjailbroken iOS6 device and it worked on it.

Nonetheless, I'm perfectly able to make in app purchases on other applications on my jailbroken device...

I tried on different Apple accounts from different countries, same results.

I also tried to delete the app and reinstall, no success.

Any idea of debug test I could do to find out the reason of the failure?
